"""add_oauth_fields

Revision ID: c336a94c7dfe
Revises: 7f6d8c9b2a31
Create Date: 2026-04-28 11:39:00.443500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c336a94c7dfe'
down_revision: Union[str, Sequence[str], None] = '7f6d8c9b2a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
